language: cpp
sudo: required
dist: bionic

# Enabling testing on Linux
#  macOS will be added later!
os:
- linux

services:
- docker

# Defining environmental variables
env:
- NUMWI=1  TESTLS=sw NRUN=1 NGEN=1
- NUMWI=1  TESTLS=sw NRUN=5 NGEN=10000
- NUMWI=8  TESTLS=sw NRUN=5 NGEN=10000
- NUMWI=16 TESTLS=sw NRUN=5 NGEN=10000
- NUMWI=1  TESTLS=ad NRUN=1 NGEN=1
- NUMWI=1  TESTLS=ad NRUN=1 NGEN=15000
- NUMWI=8  TESTLS=ad NRUN=1 NGEN=15000
- NUMWI=16 TESTLS=ad NRUN=2 NGEN=15000

before_install:
- export GIT_BRANCH=docker
- export GIT_SLUG=L30nardoSV/AutoDock-GPU
- docker build --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} -t adgpu .

script:
- export numwi=${NUMWI}
- export lsmet=${TESTLS}
- export nrun=${NRUN}
- export ngen=${NGEN}
- docker run -e numwi -e lsmet -e nrun -e ngen adgpu
