language: cpp
sudo: required
dist: bionic

# Enabling testing on Linux
#  macOS will be added later!
os:
- linux

services:
- docker

# Defining environmental variables
env:
- TESTLS=sw
- TESTLS=ad

before_install:
- export GIT_SLUG=L30nardoSV/AutoDock-GPU
- export GIT_BRANCH=docker
- docker build --build-arg cxx_compiler=${CXX_COMPILER} --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} -t adgpu .

script:
- docker run adgpu lsmet=${TESTLS}
