language: cpp
sudo: required
dist: bionic

# Enabling testing on Linux
#  macOS will be added later!
os:
- linux

services:
- docker

# Defining environmental variables
env:
- CXX_COMPILER=g++-7 TARGET=opencl
- CXX_COMPILER=clang++-6.0 TARGET=opencl

before_install:
- export GIT_SLUG=L30nardoSV/AutoDock-GPU
- export GIT_BRANCH=docker
- docker build --build-arg cxx_compiler=${CXX_COMPILER} --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} --build-arg target=${TARGET} .

script:
- docker run adgpu
