language: cpp

services:
- docker

# Defining environmental variables
env:
- NUMWI=1
- NUMWI=4
- NUMWI=8
- NUMWI=16

jobs:
    include:
        - os: linux
          dist: focal
          sudo: required
        - os: linux 
          dist: bionic
          sudo: required

before_install:
- export GIT_BRANCH=docker
- export GIT_SLUG=L30nardoSV/AutoDock-GPU
- docker build --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} -t adgpu .

script:
- export numwi=${NUMWI}
- docker run -e numwi adgpu
