language: cpp

services:
- docker

# Defining environmental variables
env:
- NUMWI=1  LSMET=sw NRUN=1 NGEN=1
- NUMWI=1  LSMET=sw NRUN=5 NGEN=10000
- NUMWI=8  LSMET=sw NRUN=5 NGEN=10000
- NUMWI=16 LSMET=sw NRUN=5 NGEN=10000
- NUMWI=1  LSMET=ad NRUN=1 NGEN=1
- NUMWI=1  LSMET=ad NRUN=1 NGEN=15000
- NUMWI=8  LSMET=ad NRUN=1 NGEN=15000
- NUMWI=16 LSMET=ad NRUN=2 NGEN=15000

jobs:
    include:
        - os: linux
          dist: focal
          sudo: required
        - os: linux 
          dist: bionic
          sudo: required

before_install:
- export GIT_BRANCH=docker
- export GIT_SLUG=L30nardoSV/AutoDock-GPU
- docker build --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} -t adgpu .

script:
- export numwi=${NUMWI}
- export lsmet=${LSMET}
- export nrun=${NRUN}
- export ngen=${NGEN}
- export psize=${PSIZE}
- export resnam=${RESNAM}
- docker run -e numwi -e lsmet -e nrun -e ngen -e psize -e resnam adgpu
