language: cpp

services:
- docker

# Defining environmental variables
env:
- NUMWI=1  NRUN=1 NGEN=1
- NUMWI=1  NRUN=5 NGEN=10000
- NUMWI=8  NRUN=5 NGEN=10000
- NUMWI=16 NRUN=5 NGEN=10000

jobs:
    include:
        - os: linux
          dist: focal
          sudo: required
        - os: linux 
          dist: bionic
          sudo: required

before_install:
- export GIT_BRANCH=docker
- export GIT_SLUG=L30nardoSV/AutoDock-GPU
- docker build --build-arg git_branch=${GIT_BRANCH} --build-arg git_slug=${GIT_SLUG} -t adgpu .

script:
- export numwi=${NUMWI}
- export nrun=${NRUN}
- export ngen=${NGEN}
- docker run -e numwi -e nrun -e ngen adgpu
